//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sujitabookstore
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class sujitabooksEntities : DbContext
    {
        public sujitabooksEntities()
            : base("name=sujitabooksEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cat_table> cat_table { get; set; }
        public virtual DbSet<ordertable> ordertables { get; set; }
        public virtual DbSet<producting> productings { get; set; }
        public virtual DbSet<Ptable> Ptables { get; set; }
        public virtual DbSet<usertable> usertables { get; set; }
    }
}
