//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sujitabookstore
{
    using System;
    using System.Collections.Generic;
    
    public partial class ordertable
    {
        public int o_id { get; set; }
        public Nullable<System.DateTime> o_details { get; set; }
        public string o_address { get; set; }
        public string o_phone { get; set; }
        public Nullable<decimal> o_total { get; set; }
        public string o_status { get; set; }
        public Nullable<int> u_id { get; set; }
    
        public virtual usertable usertable { get; set; }
    }
}
