//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sujitabookstore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ptable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ptable()
        {
            this.productings = new HashSet<producting>();
            this.productings1 = new HashSet<producting>();
        }
    
        public int P_id { get; set; }
        public string P_name { get; set; }
        public decimal P_price { get; set; }
        public int P_quantity { get; set; }
        public string P_details { get; set; }
        public int cat_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<producting> productings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<producting> productings1 { get; set; }
    }
}
